### ISSUE TITLE
Provide pointer to Lua regular expressions, please?

### ISSUE THREAD

**Issue by rdpoor** [nickgammon/Regexp#3]
Nick:

Loving Regexp -- thank you.  For those of us coming from the non-Lua Regexp camp, it would be helpful to provide a pointer to Lua-style Regexp documents in your Readme or in the forum documentation.

This seems to be the authoritative reference: http://www.lua.org/manual/5.2/manual.html#6.4.1

Thanks!

**Comment by nickgammon** [comment]
See commit https://github.com/nickgammon/Regexp/commit/94599adaef9dd27facc285da12b1c89918ab81ff
