### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by SomeGuy87** [nickgammon/Regexp#4]
Hello Nick! Hope this will even be noticed since this project seems to be a bit dated. 

To keep it short: I'd like to test and possibly use this library for a new piece of hardware I'm helping to develop in the company I'm working for. What would be the license of this project? Would we be allowed to use it? 

Thank you very much in advance.

**Comment by nickgammon** [comment]
There is a license inside the .cpp file: https://github.com/nickgammon/Regexp/blob/master/Regexp.cpp

The code is basically "glue" routines for calling the pattern-matching library written for Lua by Roberto Ierusalimschy. Lua's license is here: https://www.lua.org/license.html

I think you will find the the license is liberal enough for you to use. Credit should be given to Roberto for the original code, and me for adapting it for the Arduino.

**Comment by SomeGuy87** [comment]
That was the last place where I would have looked, haha. Thank you very much for the fast response and your effort!
