### ISSUE TITLE
Support Strings vs character arrays

### ISSUE THREAD

**Issue by JamesNewton** [nickgammon/Regexp#6]
It would be great if this library supported Strings objects instead of requiring all the buffers to be character arrays.

**Comment by nickgammon** [comment]
String objects can be easily converted into character arrays with `foo.c_str()` where foo is a String.

**Comment by JamesNewton** [comment]
Yeah, but that takes time and memory... Its a valid workaround however. Thanks.

**Comment by nickgammon** [comment]
> but that takes time and memory  ...

Not really, the code is:

```c++
const char * c_str() const { return buffer; }
```

The memory is already there, and there is no real time involved, it is just returning a pointer to the internal buffer.

**Comment by JamesNewton** [comment]
Oh my. That's cool. Thanks for pointing that out.
