### ISSUE TITLE
Create tag (or release) matching the current version number 

### ISSUE THREAD

**Issue by coddingtonbear** [nickgammon/Regexp#8]
I filed a ticket to have this library added to the registry, but there's just one more thing you have to do first.
Could i convince you into either creating a tag named '0.1.0' (really, matching this -> https://github.com/nickgammon/Regexp/blob/master/library.properties#L2) pointing at the current commit, or creating a release in github ('Code' > 'Draft new Release') setting the 'Tag version' field as '0.1.0'?  Once you do that, they'll be able to add it to the registry.

Context: https://github.com/arduino/Arduino/issues/8253#issuecomment-443065202

Thanks!

**Comment by nickgammon** [comment]
Added that tag.

**Comment by coddingtonbear** [comment]
Thanks sir!
