### ISSUE TITLE
GlobalReplace(const char * pattern, char * replacement, const unsigned int) - second arg also better const char*

### ISSUE THREAD

**Issue by s-muenzel** [nickgammon/Regexp#9]
Hi,

thanks for the library, exactly what I needed.
Absolutely minor, but I always get a compiler warning for the statement

ms.GlobalReplace("\+", "[^/]*"); 

Shouldn't the second arg for
unsigned int GlobalReplace (const char * pattern, char * replacement, const unsigned int max_count = 0);
also be "const char*".
Looking at the implementation should be ok.

Regards
Stefan

**Comment by nickgammon** [comment]
You are right. Hopefully fixed in https://github.com/nickgammon/Regexp/commit/872a5c23b6c43c02016d4897f1adc1da4563154d

**Comment by s-muenzel** [comment]
Thank you.
